init express api + mws + dotenv
lincolnaleixo/Seller-Partner-API pull request #1
Opened 2021-06-03 10:39 UTC by geni94

2021-06-03 12:02 UTC, lincolnaleixo reviewed
Like we discussed, I think you're using the legacy amazon-mws library and we don't want that.

2021-06-06 22:26 UTC, lincolnaleixo requested changes
Please confirm if the amazon-sp-api wrapper is enough . This will make our project faster to implement. I'm ok with it if you checked their code and verify it's good. If so we may remove this from our tasks and remove the other repository

2021-06-06 22:26 UTC, lincolnaleixo commented on package.json
>      "amazon-sp-api": "^0.5.1",
It seems there're an already wrapper so we won't need to do the wrapper by ourselves?

2021-06-07 07:53 UTC, geni94 commented on package.json
>      "amazon-sp-api": "^0.5.1",
@lincolnaleixo the idea was to not simply create a wrapper for Amazon SP, but also an API that will work with the front end and deliver the desired functionalities. I would not recommend exposing or using this directly on the front end application, and this way we have a lot more control on what is going on. Additionally, there should be a token exchange (for the authorization), and it would be better to handle this appropriately in multiple levels/tiers, not just on the front end.
So, in short, I don't think there is any repo to be removed.

2021-06-07 09:08 UTC, geni94 commented
commit `1b36d5ebe5e48ca7fd9e7fde94156b6b65f064cb` adds the Dockerfile and a small edit for the request headers to handle CORS.

2021-06-07 11:03 UTC, lincolnaleixo commented
As we discussed on the chat we are not going to use this as monorepo

2021-06-07 11:04 UTC, merged